blank_issues_enabled: true
contact_links:
    - name: Get Help
      url: https://github.com/jsrepojs/jsrepo/discussions/new?category=help
      about: If you can't get something to work the way you expect, open a question in our discussion forums.
