name: CLI Preview
on:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
        - uses: actions/setup-node@v4
          with:
              node-version: "20"
              cache: pnpm

        - name: Install dependencies
          run: pnpm install

        - name: Build
          run: pnpm build

        - name: publish preview
          # run: |
          run: pnpm pkg-pr-new publish --bin --packageManager=pnpm