name: CLI Preview
on:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: pnpm/action-setup@v4
        - uses: actions/setup-node@v4
          with:
              node-version: "20"
              cache: pnpm

        - name: Run changed-files
          id: changed-files
          uses: tj-actions/changed-files@v44
          with:
            separator: ' '
            dir_names: 'true'
            dir_names_max_depth: '2' # truncates the path to packages/package-name
            files: |
                packages/**

        - name: Install dependencies
          run: pnpm install

        - name: Build
          run: pnpm build:cli

        - name: publish preview
          if: ${{ steps.changed-files.outputs.all_changed_files_count > 0 }}
          env:
            CHANGED_DIRS: ${{ steps.changed-files.outputs.all_changed_files }}
          # run: |
          run: pnpm dlx pkg-pr-new publish './packages/cli' --bin